name: HEXO CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.1'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Look Dir List
        run: tree -L 3 -a

      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-renderer-pug --save
          npm install hexo-renderer-sass --save

      - name: Install Hexo
        run: npm install hexo-cli -g

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "YaoBing Xiao"
          git config --global user.email "xiaoyaobing1994@gmail.com"

      - name: Generate Hexo site
        run: npx hexo generate

      - name: Generate Hexo site
        run: npx hexo clean

      - name: Deploy hexo
        run: |
          npx hexo deploy
